find_path(FONTCONFIG_INCLUDE_DIR fontconfig/fontconfig.h)
find_library(FONTCONFIG_LIBRARY NAMES fontconfig PATH_SUFFIXES lib64)

set(FONTCONFIG_INCLUDE_DIRS ${FONTCONFIG_INCLUDE_DIR})
set(FONTCONFIG_LIBRARIES ${FONTCONFIG_LIBRARY})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(FONTCONFIG
				REQUIRED_VARS FONTCONFIG_INCLUDE_DIR FONTCONFIG_LIBRARY)

mark_as_advanced(FONTCONFIG_INCLUDE_DIR FONTCONFIG_LIBRARY)
